branch-defaults:
  master:
    environment: parse-server-dev
    group_suffix: null
global:
  application_name: parse-server
  default_ec2_keyname: aws-eb
  default_platform: Node.js
  default_region: us-west-2
  profile: null
  sc: git
